# Generated by Django 4.1 on 2023-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=4)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('insight', models.TextField()),
                ('url', models.URLField()),
                ('region', models.CharField(blank=True, max_length=50)),
                ('start_year', models.CharField(blank=True, max_length=4)),
                ('impact', models.TextField(blank=True)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField(blank=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('likelihood', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
