# Generated by Django 4.1 on 2023-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_data_remove_product_category_remove_rating_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='impact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='pestle',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='published',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='sector',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='data',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
