# Generated by Django 4.1 on 2023-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_data_options_alter_data_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={},
        ),
        migrations.AlterModelTable(
            name='data',
            table=None,
        ),
    ]
