# Generated by Django 4.1 on 2023-04-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_data_options_alter_data_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': True, 'verbose_name': 'data', 'verbose_name_plural': 'datum'},
        ),
        migrations.AlterModelTable(
            name='data',
            table='data',
        ),
    ]
