# Generated by Django 4.1 on 2023-04-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_data_options_alter_data_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='IndustrySummary',
        ),
    ]
