# Generated by Django 4.1 on 2023-04-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_rename_data_industrysummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industrysummary',
            old_name='added',
            new_name='add_date',
        ),
        migrations.RenameField(
            model_name='industrysummary',
            old_name='published',
            new_name='publish_date',
        ),
    ]
