# Generated by Django 4.1 on 2023-04-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_added_industrysummary_add_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndustrySummary',
            new_name='DataIndustry',
        ),
    ]
